[tool.black]
line-length = 79

[tool.isort]
profile = "black"

[tool.bumpversion]
current_version = "0.0.4"
commit = true
tag = true
message = "v{current_version} → v{new_version}"
tag_message = "v{current_version} → v{new_version}"


[[tool.bumpversion.files]]
filename = "gather_client_ws/__init__.py"
